// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic/pkg/app"
	"basic/pkg/logger"
	"basic/source/migration"
	"basic/source/repository"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, loggerLogger *logger.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, loggerLogger)
	migrate := server.NewMigrate(db, loggerLogger)
	appApp := newApp(migrate)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var serverSet = wire.NewSet(server.NewMigrate)

// build App
func newApp(
	migrate *server.Migrate,
) *app.App {
	return app.NewApp(app.WithServer(migrate), app.WithName("demo-migrate"))
}
