// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"basic/pkg/logger"
	"basic/source/migration"
	"basic/source/repository"
	"github.com/google/wire"
	"github.com/spf13/viper"
)

// Injectors from wire.go:

func newApp(viperViper *viper.Viper, loggerLogger *logger.Logger) (*migration.Migrate, func(), error) {
	db := repository.NewDB(viperViper)
	migrate := migration.NewMigrate(db, loggerLogger)
	return migrate, func() {
	}, nil
}

// wire.go:

var RepositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository)

var MigrateSet = wire.NewSet(migration.NewMigrate)
