version: '3.8'

services:
  postgresql:
    image: postgres:latest
    container_name: my_postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sua-maeEuOdeioReact2x
      POSTGRES_DB: sua-mae
    ports:
      - "2345:5432"
   