# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.6'

    - name: Verify Modules
      run: go mod verify

    - name: Run Vulnerability Check
      run: go run golang.org/x/vuln/cmd/govulncheck@latest ./...

    - name: Run Static Analysis
      run: go run honnef.co/go/tools/cmd/staticcheck@latest -checks=all,-ST1000,-U1000 ./...

    - name: Run Golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/HEAD/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.2

    - name: Install
      run: go install ./...

    - name: Test
      run: go test -v ./...